# Created with WinGet Releaser using komac v2.11.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: ClashVergeRev.ClashVergeRev
PackageVersion: 2.2.1
InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
FileExtensions:
- clash
ProductCode: Clash Verge
ReleaseDate: 2025-03-24
AppsAndFeaturesEntries:
- ProductCode: Clash Verge
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v2.2.1/Clash.Verge_2.2.1_x64-setup.exe
  InstallerSha256: 6A2C859EB7FDF9C5659BAD4E83F421743318C85111C86E7F03C86CF6DF902189
- Architecture: arm64
  InstallerUrl: https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v2.2.1/Clash.Verge_2.2.1_arm64-setup.exe
  InstallerSha256: B4AEB6AB4CBC9EA8B021CF6AA849F4D09CD5199DBEE660CBBD9E947933C2FA0C
ManifestType: installer
ManifestVersion: 1.9.0

